[setup]
run = [
    "npx create-next-app@latest my-app --typescript --tailwind --eslint",
    "cd my-app",
    "npm install",
]

[dev]
run = ["cd my-app", "npm run dev"]

[build]
run = ["cd my-app", "npm run build", "npm run start"]
