pub fn get_template(template: Option<String>) -> &'static [u8] {
    match template {
        None => include_bytes!("templates/default.toml"),
        Some(x) => match x.to_lowercase().as_str() {
            "android" => include_bytes!("templates/android.toml"),
            "ansible" => include_bytes!("templates/ansible.toml"),
            "astro" => include_bytes!("templates/astro.toml"),
            "aws" => include_bytes!("templates/aws.toml"),
            "bun" => include_bytes!("templates/bun.toml"),
            "deno" => include_bytes!("templates/deno.toml"),
            "django" => include_bytes!("templates/django.toml"),
            "docker" => include_bytes!("templates/docker.toml"),
            "dotnet" | ".net" => include_bytes!("templates/dotnet.toml"),
            "elixir" | "phoenix" => include_bytes!("templates/elixir.toml"),
            "expo" => include_bytes!("templates/expo.toml"),
            "fastapi" => include_bytes!("templates/fastapi.toml"),
            "flutter" => include_bytes!("templates/flutter.toml"),
            "git" => include_bytes!("templates/git.toml"),
            "go" | "golang" => include_bytes!("templates/go.toml"),
            "hugo" => include_bytes!("templates/hugo.toml"),
            "java-gradle" | "gradle" => include_bytes!("templates/java-gradle.toml"),
            "java-maven" | "maven" => include_bytes!("templates/java-maven.toml"),
            "kubernetes" | "k8s" => include_bytes!("templates/kubernetes.toml"),
            "laravel" => include_bytes!("templates/laravel.toml"),
            "monorepo" => include_bytes!("templates/monorepo.toml"),
            "nestjs" | "nest" => include_bytes!("templates/nestjs.toml"),
            "nextjs" | "next" => include_bytes!("templates/nextjs.toml"),
            "node" | "nodejs" => include_bytes!("templates/node.toml"),
            "python" | "py" => include_bytes!("templates/python.toml"),
            "rails" | "ruby" => include_bytes!("templates/rails.toml"),
            "react" => include_bytes!("templates/react.toml"),
            "rust" | "rs" => include_bytes!("templates/rust.toml"),
            "svelte" | "sveltekit" => include_bytes!("templates/svelte.toml"),
            "tauri" => include_bytes!("templates/tauri.toml"),
            "terraform" | "tf" => include_bytes!("templates/terraform.toml"),
            _ => include_bytes!("templates/default.toml"),
        },
    }
}
